### ISSUE TITLE
Changing the SVGO's options

### ISSUE THREAD

**Issue by rachelwe** [andrey-hohlov/posthtml-inline-svg#6]
Hello,

First of all, thank you for your work, your plugin is very useful !
I just have a small issue : for accessibility reasons, I need to keep the title of the SVG and the SVGO config is removing them by default.

I tried using an `.svgo.yml` file to change that but it doesn't seem to have any effect. Am I missing something / doing something wrong ?

Here's my `.svgo.yml` file if it helps

```yml
# replace default svgo config

plugins:
  - removeTitle: false
```
